/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import CONTROL.ControleLivro;
import CONTROL.ControleCurso;
import MODEL.Livro;
import MODEL.Curso;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JifLivros extends javax.swing.JInternalFrame {

    /**
     * Creates new form JfAluno
     */
    public JifLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JbCarregarCampos = new javax.swing.JButton();
        JbCadastrarLivro = new javax.swing.JButton();
        JbConsultarLivro = new javax.swing.JButton();
        JbEditarLivro = new javax.swing.JButton();
        JbExcluirLivro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableLivro = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtfAutorLivro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JtfTituloLivro = new javax.swing.JTextField();
        JtfGeneroLivro = new javax.swing.JTextField();
        JtfQuantidadeEstoque = new javax.swing.JTextField();
        JtfEditoraLivro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JtfCodigoLivro = new javax.swing.JTextField();
        JtfISBNLivro = new javax.swing.JTextField();
        JtfAnoPublicacao = new javax.swing.JTextField();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Formulário Cadastro Livro");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editora");

        JbCarregarCampos.setBackground(new java.awt.Color(102, 102, 102));
        JbCarregarCampos.setForeground(new java.awt.Color(255, 255, 255));
        JbCarregarCampos.setText("CARREGAR CAMPOS");
        JbCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCarregarCamposActionPerformed(evt);
            }
        });

        JbCadastrarLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbCadastrarLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbCadastrarLivro.setText("CADASTRAR");
        JbCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarLivroActionPerformed(evt);
            }
        });

        JbConsultarLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbConsultarLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbConsultarLivro.setText("CONSULTAR");
        JbConsultarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbConsultarLivroActionPerformed(evt);
            }
        });

        JbEditarLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbEditarLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbEditarLivro.setText("EDITAR");
        JbEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbEditarLivroActionPerformed(evt);
            }
        });

        JbExcluirLivro.setBackground(new java.awt.Color(102, 102, 102));
        JbExcluirLivro.setForeground(new java.awt.Color(255, 255, 255));
        JbExcluirLivro.setText("EXCLUIR");
        JbExcluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbExcluirLivroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Título");

        JTableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "TÍTULO", "AUTOR", "EDITORA", "ANO PUBLICAÇÃO", "ISBN", "GÊNERO", "QUANT ESTOQUE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableLivro);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Autor");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ano de Publicação");

        JtfAutorLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfAutorLivroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ISBN");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gênero");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantidade de Estoque");

        JtfTituloLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfTituloLivroActionPerformed(evt);
            }
        });

        JtfQuantidadeEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfQuantidadeEstoqueActionPerformed(evt);
            }
        });

        JtfEditoraLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfEditoraLivroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Código");

        JtfCodigoLivro.setEditable(false);
        JtfCodigoLivro.setEnabled(false);
        JtfCodigoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfCodigoLivroActionPerformed(evt);
            }
        });

        JtfISBNLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfISBNLivroActionPerformed(evt);
            }
        });

        JtfAnoPublicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfAnoPublicacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(370, 370, 370))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(20, 20, 20)
                                .addComponent(JtfCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(JtfTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5)
                                .addGap(20, 20, 20)
                                .addComponent(JtfAutorLivro))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JtfGeneroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JtfEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel6)
                                        .addGap(20, 20, 20)
                                        .addComponent(JtfAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(20, 20, 20)
                                        .addComponent(JtfISBNLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(JtfQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JbCadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbConsultarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbEditarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbExcluirLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbCarregarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(198, 198, 198))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JtfCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JtfTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JtfAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtfEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(JtfISBNLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JtfAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JtfGeneroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(JtfQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCadastrarLivro)
                    .addComponent(JbConsultarLivro)
                    .addComponent(JbEditarLivro)
                    .addComponent(JbExcluirLivro)
                    .addComponent(JbCarregarCampos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCarregarCamposActionPerformed
        // TODO add your handling code here:
        carregarCampos();

    }//GEN-LAST:event_JbCarregarCamposActionPerformed

    private void JbCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarLivroActionPerformed
        // TODO add your handling code here:
        cadastrarLivroView();
        limparCampos();

    }//GEN-LAST:event_JbCadastrarLivroActionPerformed

    private void JbConsultarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbConsultarLivroActionPerformed
        // TODO add your handling code here:
        listarLivroView();
    }//GEN-LAST:event_JbConsultarLivroActionPerformed

    private void JbEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbEditarLivroActionPerformed
        // TODO add your handling code here:
        alterarLivroView();
        listarLivroView();
        limparCampos();

    }//GEN-LAST:event_JbEditarLivroActionPerformed

    private void JbExcluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbExcluirLivroActionPerformed
        // TODO add your handling code here:
        excluirLivroView();
        limparCampos();

    }//GEN-LAST:event_JbExcluirLivroActionPerformed

    private void JtfQuantidadeEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfQuantidadeEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfQuantidadeEstoqueActionPerformed

    private void JtfEditoraLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfEditoraLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfEditoraLivroActionPerformed

    private void JtfCodigoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfCodigoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfCodigoLivroActionPerformed

    private void JtfTituloLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfTituloLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfTituloLivroActionPerformed

    private void JtfISBNLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfISBNLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfISBNLivroActionPerformed

    private void JtfAutorLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfAutorLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfAutorLivroActionPerformed

    private void JtfAnoPublicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfAnoPublicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfAnoPublicacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableLivro;
    private javax.swing.JButton JbCadastrarLivro;
    private javax.swing.JButton JbCarregarCampos;
    private javax.swing.JButton JbConsultarLivro;
    private javax.swing.JButton JbEditarLivro;
    private javax.swing.JButton JbExcluirLivro;
    private javax.swing.JTextField JtfAnoPublicacao;
    private javax.swing.JTextField JtfAutorLivro;
    private javax.swing.JTextField JtfCodigoLivro;
    private javax.swing.JTextField JtfEditoraLivro;
    private javax.swing.JTextField JtfGeneroLivro;
    private javax.swing.JTextField JtfISBNLivro;
    private javax.swing.JTextField JtfQuantidadeEstoque;
    private javax.swing.JTextField JtfTituloLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

     private void cadastrarLivroView(){
        if(validarCampos()){
            try {
                Livro objLivro = new Livro();
                objLivro.setTitulo_livro(JtfTituloLivro.getText());
                objLivro.setAutor(JtfAutorLivro.getText());
                objLivro.setEditora(JtfEditoraLivro.getText());
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
                Date anoPublicacao = sdf.parse(JtfAnoPublicacao.getText());
                objLivro.setAno_publicacao(anoPublicacao);
                
                objLivro.setIsbn(JtfISBNLivro.getText());
                objLivro.setGenero(JtfGeneroLivro.getText());
                objLivro.setQuantidade_estoque(Integer.parseInt(JtfQuantidadeEstoque.getText()));
                
                ControleLivro objControleLivro = new ControleLivro();
                objControleLivro.cadastrarLivro(objLivro);
                JOptionPane.showMessageDialog(null, "Livro Cadastrado com Sucesso!!!");
                listarLivroView();
                
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar livro: " + erro.getMessage() );
            }
        }
    }
    
    private void listarLivroView(){
        try {
            ControleLivro objControleLivro = new ControleLivro();
            DefaultTableModel model = (DefaultTableModel) JTableLivro.getModel();
            
            model.setRowCount(0);
            
            ArrayList<Livro> lista = objControleLivro.consultarLivro();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
            
            for(int num = 0; num < lista.size(); num++){
                String dataFormatada = sdf.format(lista.get(num).getAno_publicacao());
                
                model.addRow(new Object[]{
                    lista.get(num).getId_livro(),
                    lista.get(num).getTitulo_livro(),
                    lista.get(num).getAutor(),
                    lista.get(num).getEditora(),
                    dataFormatada,
                    lista.get(num).getIsbn(),
                    lista.get(num).getGenero(),
                    lista.get(num).getQuantidade_estoque()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar livros: " + erro.getMessage());
        }
    }
    
    private void carregarCampos(){
        int linha = JTableLivro.getSelectedRow();
        if (linha != -1) {
            JtfCodigoLivro.setText(JTableLivro.getValueAt(linha, 0).toString());
            JtfTituloLivro.setText(JTableLivro.getValueAt(linha, 1).toString());
            JtfAutorLivro.setText(JTableLivro.getValueAt(linha, 2).toString());
            JtfEditoraLivro.setText(JTableLivro.getValueAt(linha, 3).toString());
            JtfAnoPublicacao.setText(JTableLivro.getValueAt(linha, 4).toString());
            JtfISBNLivro.setText(JTableLivro.getValueAt(linha, 5).toString());
            JtfGeneroLivro.setText(JTableLivro.getValueAt(linha, 6).toString());
            JtfQuantidadeEstoque.setText(JTableLivro.getValueAt(linha, 7).toString());
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um livro da tabela para carregar os campos");
        }
    }
    
    private void alterarLivroView(){
        if(JtfCodigoLivro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um livro para editar");
            return;
        }
        if(validarCampos()){
            try{
                Livro objLivro = new Livro();
                objLivro.setId_livro(Integer.parseInt(JtfCodigoLivro.getText()));
                objLivro.setTitulo_livro(JtfTituloLivro.getText());
                objLivro.setAutor(JtfAutorLivro.getText());
                objLivro.setEditora(JtfEditoraLivro.getText());
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
                Date anoPublicacao = sdf.parse(JtfAnoPublicacao.getText());
                objLivro.setAno_publicacao(anoPublicacao);
                
                objLivro.setIsbn(JtfISBNLivro.getText());
                objLivro.setGenero(JtfGeneroLivro.getText());
                objLivro.setQuantidade_estoque(Integer.parseInt(JtfQuantidadeEstoque.getText()));
                
                ControleLivro objControleLivro = new ControleLivro();
                objControleLivro.alterarLivro(objLivro);
                JOptionPane.showMessageDialog(null, "Livro alterado com sucesso!");
                
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro ao alterar livro: " + erro.getMessage());
            }
        }
    } 
    
    private void excluirLivroView(){
        if (JtfCodigoLivro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um livro para excluir");
            return;
        }
        
        int confirmar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este livro?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if(confirmar == JOptionPane.YES_OPTION){
            try {
                Livro objLivro = new Livro();
                objLivro.setId_livro(Integer.parseInt(JtfCodigoLivro.getText()));
                
                ControleLivro objControleLivro = new ControleLivro();
                objControleLivro.excluirLivro(objLivro);
                JOptionPane.showMessageDialog(null, "Livro Excluído com Sucesso");
                listarLivroView();
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir livro: " + erro.getMessage());
            }
        }
    }
    
    private void limparCampos(){
        JtfCodigoLivro.setText("");
        JtfTituloLivro.setText("");
        JtfAutorLivro.setText("");
        JtfEditoraLivro.setText("");
        JtfAnoPublicacao.setText("");
        JtfISBNLivro.setText("");
        JtfGeneroLivro.setText("");
        JtfQuantidadeEstoque.setText("0");
        JtfTituloLivro.requestFocus();
    }
    
    private boolean validarCampos(){
        if (JtfTituloLivro.getText().isEmpty()
            || JtfAutorLivro.getText().isEmpty()
            || JtfEditoraLivro.getText().isEmpty()
            || JtfAnoPublicacao.getText().isEmpty()
            || JtfISBNLivro.getText().isEmpty()
            || JtfGeneroLivro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios!");
            return false;
        }
        
        // Validar se a quantidade é numérica
        try {
            int quantidade = Integer.parseInt(JtfQuantidadeEstoque.getText());
            if (quantidade < 0) {
                JOptionPane.showMessageDialog(null, "A quantidade não pode ser negativa!");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A quantidade deve conter apenas números");
            return false;
        }
        
        // Validar se a data está completa "dd/mm/yyyy"
        if (JtfAnoPublicacao.getText().contains(" ")){
            JOptionPane.showMessageDialog(null, "Data de publicação inválida!");
            return false;
        }
        
        return true;
    }
}
